package com.alextos.contactsapp.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xff006e2f)
val OnPrimaryLight = Color(0xffffffff)
val PrimaryContainerLight = Color(0xff9af7a8)
val OnPrimaryContainerLight = Color(0xff002109)
val SecondaryLight = Color(0xff516351)
val OnSecondaryLight = Color(0xffffffff)
val SecondaryContainerLight = Color(0xffd4e8d1)
val OnSecondaryContainerLight = Color(0xff0f1f11)
val TertiaryLight = Color(0xff39656d)
val OnTertiaryLight = Color(0xffffffff)
val TertiaryContainerLight = Color(0xffbdeaf3)
val OnTertiaryContainerLight = Color(0xff001f24)
val ErrorLight = Color(0xffba1a1a)
val OnErrorLight = Color(0xffffffff)
val ErrorContainerLight = Color(0xffffdad6)
val OnErrorContainerLight = Color(0xff410002)
val BackgroundLight = Color(0xfffcfdf7)
val OnBackgroundLight = Color(0xff1a1c19)
val SurfaceLight = Color(0xfffcfdf7)
val OnSurfaceLight = Color(0xff1a1c19)
val OutlineLight = Color(0xff727970)
val SurfaceVariantLight = Color(0xffdde5da)
val OnSurfaceVariantLight = Color(0xff414941)

val PrimaryDark = Color(0xff7fda8e)
val OnPrimaryDark = Color(0xff003915)
val PrimaryContainerDark = Color(0xff005321)
val OnPrimaryContainerDark = Color(0xff9af7a8)
val SecondaryDark = Color(0xff516351)
val OnSecondaryDark = Color(0xffffffff)
val SecondaryContainerDark = Color(0xffd4e8d1)
val OnSecondaryContainerDark = Color(0xffd4e8d1)
val TertiaryDark = Color(0xff39656d)
val OnTertiaryDark = Color(0xffffffff)
val TertiaryContainerDark = Color(0xffbdeaf3)
val OnTertiaryContainerDark = Color(0xffbdeaf3)
val ErrorDark = Color(0xffba1a1a)
val OnErrorDark = Color(0xffffffff)
val ErrorContainerDark = Color(0xffffdad6)
val OnErrorContainerDark = Color(0xffffdad6)
val BackgroundDark = Color(0xfffcfdf7)
val OnBackgroundDark = Color(0xff1a1c19)
val SurfaceDark = Color(0xfffcfdf7)
val OnSurfaceDark = Color(0xff1a1c19)
val OutlineDark = Color(0xff727970)
val SurfaceVariantDark = Color(0xffdde5da)
val OnSurfaceVariantDark = Color(0xff414941)